### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by dermetfan** [tommyettinger/gdx-utils#1]
The old wiki is now up on [sourcehut](https://man.sr.ht/~dermetfan/libgdx-utils/).

Maybe you want to fork it or link to it in the readme.

I'm happy some still see value in my teenage project!

**Comment by tommyettinger** [comment]
Yay! I know people still use this, and I was not happy that BitBucket was unceremoniously dumping so many people's hard work. I'll add the wiki to the readme, thanks!
